### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WaldperlachFabi** [czQery/ToolKit#3]
Hello in my console is always this error: 
[Tue, 9. Nov 2021 17:11:31 UTC WARN] Plugin ToolKit v2.8 generated an exception while executing task 525 
what can I do to fix this?

**Comment by czQery** [comment]
Hi,
What server version are you running?
Does it happen randomly, at startup or when using a command?

Send the rest of the error message there should be details below it, something like this:
```log
[02:44:45] [Craft Scheduler Thread - 281/WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b699 generated an exception while executing task 31
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more
```

**Comment by WaldperlachFabi** [comment]
No nothing… my server is running on paper 1.17.1 this message is coming every minute but nothing more:
[Tue, 9. Nov 2021 19:15:00 UTC WARN] Plugin ToolKit v2.8 generated an exception while executing task 522

**Comment by czQery** [comment]
There is only one thing that happen periodically every minute and that is lunar waypoint update.
I forgot to implement waypoint config check, so there's a chance you have some incorrect data in it.

Maybe world that doesnt exist or invalid hex color etc.
Here's an example of what a valid waypoint save looks like:
```yaml
 waypoints:
  - Spawn:
      name: Spawn
      color: '#ba1e0d'
      world: world
      x: 0
      y: 100
      z: 0
```

**Comment by WaldperlachFabi** [comment]
Hello, this is my config, I think everything is right: 
join:
  alert: false
  message: '&8[&cSERVER&8]&6 %player%&7 joined!'
  teleport: true
  world: world
leave:
  alert: false
  message: '&8[&cSERVER&8]&6 %player%&7 disconnected!'
color:
  bracket: '&8'
  name: '&c'
  text: '&7'
  highlight: '&6'
lunar:
  kick: false
  kick_message: '&8[&cSERVER&8]&7 This is lunar only server!'
  waypoints:
  - Spawn:
      name: Spawn
      color: '#ba1e0d'
      world: world
      x: 0
      y: 100
      z: 0
  disabled_mods:
  - freelook

**Comment by czQery** [comment]
Try new version, and reopen the issue if the problem still occurs.

**Comment by WaldperlachFabi** [comment]
How exactly can i disable lunar waypoint with the new version? And can you please add console support for /crash? Thank you for your help!

**Comment by WaldperlachFabi** [comment]
Ok just disabled it with -waypoints! But could you please add console support dor /crash ? Would be really nice to troll some Friends with this!

**Comment by czQery** [comment]
There is /crash support in console.
![Screenshot 2021-11-11 210757](https://user-images.githubusercontent.com/60880179/141362088-a3ba6664-0ce0-47a2-ad43-73aae95d7878.png)

Just delete the waypoints section in the config:
```yaml
join:
  alert: false
  message: '&8[&cSERVER&8]&6 %player%&7 joined!'
  teleport: true
  world: world
leave:
  alert: false
  message: '&8[&cSERVER&8]&6 %player%&7 disconnected!'
color:
  bracket: '&8'
  name: '&c'
  text: '&7'
  highlight: '&6'
lunar:
  kick: false
  kick_message: '&8[&cSERVER&8]&7 This is lunar only server!'
```
