### ISSUE TITLE
Lunar mod "Kick all Lunar clients" mod not there

### ISSUE THREAD

**Issue by KadTheAad** [czQery/ToolKit#7]
Title

**Comment by czQery** [comment]
Is this a feature request?
Since there is no such feature mentioned anywhere (unless it's a typo), there is only the kicking out non lunar players right after they connect (something like a lunar only whitelist)
And if that's what you're thinking, you need to enter this into your config:

```yml
lunar:
  kick: true
  kick_message: '&8[&cSERVER&8]&7 This is lunar only server!'
```
